name: Build Android App
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "11"
      - uses: android-actions/setup-android-sdk@v2
        with:
          sdk-platform: "android-30"
          ndk-version: "22.1.7171670"
          java-version: "11"
          emulator-version: "30.9.4"
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Build the app
        run: ./gradlew assembleDebug
